name: Laravel CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode
      - name: Checkout kode
        uses: actions/checkout@v3

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      # 3. Setup folder Laravel (WAJIB sebelum composer)
      - name: Setup Laravel directories
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          mkdir -p bootstrap/cache
          chmod -R 777 storage bootstrap/cache

      # 4. Install dependency
      - name: Install dependency
        run: composer install

      # 5. Copy env
      - name: Copy .env
        run: cp .env.example .env

      # 6. Setup database file
      - name: Setup SQLite
        run: touch database/database.sqlite

      # 7. Configure database
      - name: Configure database
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's|DB_DATABASE=.*|DB_DATABASE=database/database.sqlite|' .env

      # 8. Generate key
      - name: Generate key
        run: php artisan key:generate

      # 9. Run migration
      - name: Run migration
        run: php artisan migrate --force

      # 10. Run test
      - name: Run test
        run: php artisan test